name: Proxy Filter
on:
  schedule: [ { cron: '0 * * * *' } ]
  push: { branches: [ main ] }
  workflow_dispatch:

concurrency: { group: proxy-filter, cancel-in-progress: true }

jobs:
  filter:
    runs-on: ubuntu-latest
    permissions: { contents: write }

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with: { python-version: '3.12' }

    - name: Install sing-box
      run: |
        set -euo pipefail
        case "$(uname -m)" in
          x86_64|amd64)  ARCH=linux-amd64  ;;
          aarch64|arm64) ARCH=linux-arm64  ;;
          *) echo "unsupported arch"; exit 1 ;;
        esac
        VER=$(curl -sSL https://api.github.com/repos/SagerNet/sing-box/releases/latest \
              | grep -Po '"tag_name":\s*"\K[^"]+')
        V=${VER#v}
        BASE="https://github.com/SagerNet/sing-box/releases/download/$VER/sing-box-$V-$ARCH"
        (curl -fLS "$BASE.tar.gz" | tar -xz --strip-components=1 -C /usr/local/bin sing-box) \
          || curl -fLS "$BASE" -o /usr/local/bin/sing-box
        chmod +x /usr/local/bin/sing-box
        sing-box version

    - name: Install deps
      run: pip install --quiet pyyaml

    - name: Run proxy filter
      run: python test_servers.py --output output/Server.txt

    - uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "chore: update proxy lists [skip ci]"
        file_pattern: output/**          # ← коммитим вообще всё в папке
        push_options: '--force-with-lease'

    - uses: actions/upload-artifact@v4
      if: always()
      with: { name: proxy-results, path: output/** }