name: Proxy Filter

on:
  schedule:
    - cron:  '0 * * * *'
  push: { branches: [ main ] }
  workflow_dispatch:

concurrency:
  group: proxy-filter
  cancel-in-progress: true

jobs:
  filter:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with: { python-version: '3.12' }

    # ─── install sing-box ────────────────────────────────────────────────
    - name: Install sing-box
      run: |
        arch="$(uname -m)"
        url="https://github.com/SagerNet/sing-box/releases/latest/download/sing-box-$arch-unknown-linux-gnu.tar.gz"
        curl -L "$url" | tar -xz --strip-components=1 -C /usr/local/bin sing-box
        chmod +x /usr/local/bin/sing-box
        sing-box --version

    - name: Install Python deps
      run: pip install --quiet pyyaml

    - name: Run proxy filter
      run: python test_servers.py --output output/Server.txt

    - name: Commit & push
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "chore: update proxy lists [skip ci]"
        file_pattern: |
          output/Server.txt
        push_options: '--force-with-lease'

    - name: Upload artifact
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: proxy-results
        path: output/Server.txt