name: Proxy Filter
on:
  workflow_dispatch:
  schedule:
    - cron: "17 * * * *"        # каждые час-семнадцать

jobs:
  filter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with: { python-version: '3.x' }

      - name: Install deps
        run: python -m pip install --upgrade pip

      - name: Run proxy filter
        run: python test_servers.py

      - name: Commit & push result
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: update proxy lists
          file_pattern: |
            output/Server.txt
            output/latency.csv
            output/debug.log