name: Proxy Filter

on:
  workflow_dispatch:          # запуск вручную по кнопке “Run workflow”
  schedule:                   # запуск по расписанию (UTC)
    - cron: '0 * * * *'       # каждый час, ровно в 00 минут

jobs:
  filter:
    runs-on: ubuntu-latest

    steps:
      # 1. получаем код репозитория
      - name: Checkout repo
        uses: actions/checkout@v4

      # 2. ставим Python 3.13
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      # 3. зависимости для скрипта
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install aiohttp

      # 4. прогоняем фильтр-скрипт
      - name: Run proxy filter
        run: python test_servers.py

      # 5. коммитим результаты (список, логи и т. д.)
      - name: Commit & push result
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: chore: update proxy lists
          file_pattern: |
            output/Server.txt
            output/*.log