name: Proxy Filter

on:
  schedule: [{ cron: '0 * * * *' }]   # каждый час
  push:     { branches: [ main ] }
  workflow_dispatch:

concurrency: { group: proxy-filter, cancel-in-progress: true }

jobs:
  filter:
    runs-on: ubuntu-latest
    permissions: { contents: write }

    steps:
    # 1 — код репозитория
    - uses: actions/checkout@v4

    # 2 — Python 3.12
    - uses: actions/setup-python@v5
      with: { python-version: '3.12' }

    # 3 — robust-установка sing-box
    - name: Install sing-box
      run: |
        set -euo pipefail
        case "$(uname -m)" in
          x86_64|amd64)  PATTERN=linux-amd64  ;;
          aarch64|arm64) PATTERN=linux-arm64  ;;
          *) echo "✖ unsupported arch"; exit 1 ;;
        esac

        # URL первого подходящего asset'а
        ASSET=$(curl -fsSL https://api.github.com/repos/SagerNet/sing-box/releases/latest |
                grep -Po '"browser_download_url":\s*"\K[^"]+' |
                grep "$PATTERN" | head -n1)

        [ -z "$ASSET" ] && { echo "✖ sing-box asset not found"; exit 1; }
        echo "⬇  $ASSET"

        TMP=$(mktemp -d)
        if [[ $ASSET == *.tar.gz ]]; then
          curl -fsSL "$ASSET" -o "$TMP/sb.tgz"
          tar -xzf "$TMP/sb.tgz" -C "$TMP"
          BIN=$(find "$TMP" -type f -name sing-box | head -n1)
          [ -z "$BIN" ] && { echo "✖ binary not in archive"; exit 1; }
          sudo install -m755 "$BIN" /usr/local/bin/sing-box
        else
          sudo curl -fsSL "$ASSET" -o /usr/local/bin/sing-box
          sudo chmod 755 /usr/local/bin/sing-box
        fi

        /usr/local/bin/sing-box version

    # 4 — Python-deps
    - name: Install Python deps
      run: pip install --quiet pyyaml

    # 5 — фильтруем прокси
    - name: Run proxy filter
      run: python test_servers.py --output output/Server.txt

    # 6 — коммитим всё из output/
    - uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "chore: update proxy list [skip ci]"
        file_pattern: output/**
        push_options: "--force-with-lease"

    # 7 — артефакт
    - uses: actions/upload-artifact@v4
      if: always()
      with: { name: proxy-results, path: output/** }