name: Proxy Filter

on:
  workflow_dispatch:      # ручной запуск
  schedule:               # + ежечасовой крон
    - cron:  '0 * * * *'  # (UTC)

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set-up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install requirements
        run: |
          python -m pip install -r requirements.txt

      - name: Run proxy filter
        run: |
          python test_servers.py \
            --sources sources.txt \
            --output  output/Server.txt \
            --debug   output/debug.log \
            --probe   http \
            --max     20 \
            --drop-ports 8880 \
            --drop-proto ss,ssr \
            --unique-country \
            --min-succ 1 \
            --max-rtt   800