name: Proxy Filter

on:
  workflow_dispatch:            # ручной старт
  schedule:
    - cron: '0 * * * *'         # каждый час (UTC)

jobs:
  filter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Ensure output folder exists and clear old list
        run: |
          mkdir -p output
          : > output/Server.txt        # truncate (пустой файл)

      - name: Run proxy filter
        run: |
          python test_servers.py \
            --sources  sources.txt \
            --output   output/Server.txt \
            --debug    output/debug.log