name: Proxy Filter

on:
  schedule:
    - cron:  '0 * * * *'   # каждый час
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  filter:
    runs-on: ubuntu-latest
    permissions:
      contents: write        # нужно, чтобы пушить изменения

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyyaml        # нужна для clashx_pro.yaml

    - name: Run proxy filter
      run: python test_servers.py --output output/Server.txt

    - name: Commit & push result
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "chore: update proxy lists [skip ci]"
        file_pattern: |
          output/Server.txt
          output/skipped.txt
          output/ping_debug.txt
          output/clashx_pro.yaml

    - name: Upload artifacts
      if: always()               # даже если предыдущие шаги упали
      uses: actions/upload-artifact@v4
      with:
        name: proxy-results
        path: |
          output/Server.txt
          output/skipped.txt
          output/ping_debug.txt
          output/clashx_pro.yaml
