name: proxy_filter

on:
  workflow_dispatch:           # ручной запуск в-вкладке Actions
  schedule:
    - cron:  '0 * * * *'       # раз в час

jobs:
  run-filter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install requirements
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run proxy filter
        run: |
          python test_servers.py \
            --sources  sources.txt \
            --output   output/Server.txt \
            --debug    output/debug.log

      - name: Commit results if changed
        run: |
          git config user.name  "proxy-bot"
          git config user.email "bot@users.noreply.github.com"
          git add output/Server.txt output/debug.log || true
          if ! git diff --cached --quiet; then
            git commit -m "auto: update proxy list"
            git push
          fi