name: Proxy Filter

on:
  workflow_dispatch:        # ручной запуск из вкладки Actions
  schedule:
    - cron: '0 * * * *'     # каждый час (UTC)

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: pip

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip  install aiohttp async_timeout

      - name: Run proxy filter
        run: |
          python test_servers.py \
            --sources  sources.txt \
            --output   output/Server.txt \
            --debug    output/debug.log \
            --probe    http \
            --min-speed 100 \
            --max-rtt   800 \
            --min-succ  1 \
            --drop-ports 8880 \
            --drop-proto ss,ssr \
            --max 20

      - name: Commit & push results
        if: success()
        run: |
          git config --global user.email  "actions@github.com"
          git config --global user.name   "GitHub Actions"
          git add output/*
          git commit -m "Update proxies $(date -u +'%Y-%m-%d %H:%M')"
          git push || echo "No changes"