name: proxy_filter

on:
  schedule:
    - cron:  '0 * * * *'      # каждый час (UTC)
  workflow_dispatch:          # кнопка «Run workflow»

jobs:
  filter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with: { python-version: '3.11', cache: pip }

      - name: Install deps
        run: |
          python -m pip install -r requirements.txt

      - name: Run proxy filter
        run: |
          python test_servers.py \
            --sources  sources.txt \
            --output   output/Server.txt \
            --debug    output/debug.log \
            --max      20 \
            --probe    http \
            --drop-ports 8880 \
            --drop-proto ss,ssr \
            --unique-country \
            --min-speed 200

      - name: Commit results
        run: |
          git config user.name  "proxy-bot"
          git config user.email "proxy-bot@users.noreply.github.com"
          git add output/Server.txt output/debug.log
          git diff --cached --quiet || git commit -m "auto: refresh proxies"
          git push