name: Proxy Filter

on:
  schedule:
    - cron:  '0 * * * *'          # каждый час
  push: { branches: [ main ] }
  workflow_dispatch:

concurrency:
  group: proxy-filter
  cancel-in-progress: true

jobs:
  filter:
    runs-on: ubuntu-latest
    permissions:
      contents: write             # чтобы бот мог пушить

    steps:
    # ─── 1. код репозитория ────────────────────────────────────────────────
    - uses: actions/checkout@v4

    # ─── 2. Python 3.12 ────────────────────────────────────────────────────
    - uses: actions/setup-python@v5
      with: { python-version: '3.12' }

    # ─── 3. sing-box (статический бинарник) ────────────────────────────────
    - name: Install sing-box
      run: |
        set -euo pipefail

        case "$(uname -m)" in
          x86_64|amd64) BIN=sing-box-linux-amd64  ;;
          aarch64|arm64) BIN=sing-box-linux-arm64 ;;
          *) echo "✖ Unsupported arch" ; exit 1 ;;
        esac

        URL="https://github.com/SagerNet/sing-box/releases/latest/download/${BIN}"
        echo "Downloading $URL"
        curl -sSL "$URL" -o /usr/local/bin/sing-box
        chmod +x /usr/local/bin/sing-box
        sing-box version               # проверка

    # ─── 4. Python-зависимости ─────────────────────────────────────────────
    - name: Install Python deps
      run: pip install --quiet pyyaml

    # ─── 5. Запускаем фильтр ───────────────────────────────────────────────
    - name: Run proxy filter
      run: python test_servers.py --output output/Server.txt

    # ─── 6. Коммитим результат ─────────────────────────────────────────────
    - uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "chore: update proxy lists [skip ci]"
        file_pattern: |
          output/Server.txt
          output/latency_full.csv
        push_options: '--force-with-lease'

    # ─── 7. Артефакт (на всякий случай) ───────────────────────────────────
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: proxy-results
        path: |
          output/Server.txt
          output/latency_full.csv