name: Proxy Filter / filter

on:
  schedule:
    - cron: '6 * * * *'        # каждый час + несколько минут «сдвига»
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v4

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install aiohttp async_timeout

      - name: Run proxy filter
        run: |
          python test_servers.py \
            --sources  sources.txt \
            --output   output/Server.txt \
            --debug    output/debug.log \
            --max      20 \
            --probe    http \
            --drop-ports 8880 \
            --drop-proto ss,ssr \
            --unique-country \
            --min-speed 200

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: proxy-results
          path: |
            output/Server.txt
            output/debug.log
            output/latency.csv