name: Proxy Filter
on:
  schedule: [{ cron: '0 * * * *' }]
  push:     { branches: [ main ] }
  workflow_dispatch:

concurrency: { group: proxy-filter, cancel-in-progress: true }

jobs:
  filter:
    runs-on: ubuntu-latest
    permissions: { contents: write }

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with: { python-version: '3.12' }

    # ───────────────────── install sing-box ─────────────────────
    - name: Install sing-box
      run: |
        set -euo pipefail
        arch=$(uname -m)
        patn=$([[ $arch =~ (x86_64|amd64) ]] && echo linux-amd64 || echo linux-arm64)

        url=$(curl -fsSL https://api.github.com/repos/SagerNet/sing-box/releases/latest |
              grep -Po '"browser_download_url":\s*"\K[^"]+' | grep "$patn" | head -n1)
        [ -z "$url" ] && { echo "asset not found"; exit 1; }
        echo "asset ← $url"

        if [[ $url =~ \.tar\.gz$ ]]; then
          # извлекаем ТОЛЬКО бинарник и пишем прямо в /usr/local/bin
          curl -fsSL "$url" | tar -xzO --wildcards --no-anchored '*/sing-box' \
            | sudo tee /usr/local/bin/sing-box >/dev/null
        else
          sudo curl -fsSL "$url" -o /usr/local/bin/sing-box
        fi
        sudo chmod 755 /usr/local/bin/sing-box
        sing-box version

    # ───────────────────── deps & run ───────────────────────────
    - name: Install deps
      run: pip install --quiet pyyaml

    - name: Run proxy filter
      run: python test_servers.py --output output/Server.txt

    # ───────────────────── commit & artifact ────────────────────
    - uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "chore: update proxy list [skip ci]"
        file_pattern: output/**
        push_options: '--force-with-lease'

    - uses: actions/upload-artifact@v4
      if: always()
      with: { name: proxy-results, path: output/** }