name: Proxy Filter
on:
  schedule: [{ cron: '0 * * * *' }]
  push: { branches: [main] }
  workflow_dispatch:
concurrency: { group: proxy-filter, cancel-in-progress: true }

jobs:
  filter:
    runs-on: ubuntu-latest
    permissions: { contents: write }

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with: { python-version: '3.12' }

    - name: Install sing-box
      run: |
        set -euo pipefail
        case $(uname -m) in x86_64|amd64) PATTERN=linux-amd64;; aarch64|arm64) PATTERN=linux-arm64;; *) exit 1;; esac
        ASSET=$(curl -s https://api.github.com/repos/SagerNet/sing-box/releases/latest |
                grep -Po '"browser_download_url": *"\K[^"]+' | grep "$PATTERN" | head -n1)
        echo "asset: $ASSET"
        TMP=$(mktemp -d)
        if [[ $ASSET == *.tar.gz ]]; then
          curl -sL $ASSET -o $TMP/sb.tgz && tar -xzf $TMP/sb.tgz -C $TMP
          mv $(find $TMP -name sing-box|head -n1) /usr/local/bin/sing-box
        else
          curl -sL $ASSET -o /usr/local/bin/sing-box
        fi
        chmod +x /usr/local/bin/sing-box && sing-box version

    - name: Install deps
      run: pip install --quiet pyyaml

    - name: Run proxy filter
      run: python test_servers.py --output output/Server.txt

    - uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "chore: update proxy list [skip ci]"
        file_pattern: output/**
        push_options: "--force-with-lease"

    - uses: actions/upload-artifact@v4
      if: always()
      with: { name: proxy-results, path: output/** }