name: Proxy Filter

on:
  schedule:
    - cron:  '0 * * * *'          # каждый час
  push: { branches: [ main ] }
  workflow_dispatch:

concurrency:
  group: proxy-filter
  cancel-in-progress: true

jobs:
  filter:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    # ─── 1. репозиторий ────────────────────────────────────────────────────
    - uses: actions/checkout@v4

    # ─── 2. Python 3.12 ────────────────────────────────────────────────────
    - uses: actions/setup-python@v5
      with: { python-version: '3.12' }

    # ─── 3. установка sing-box ─────────────────────────────────────────────
    - name: Install sing-box
      run: |
        set -euo pipefail

        # архитектура runner’а
        case "$(uname -m)" in
          x86_64|amd64) SB_ARCH=linux-amd64  ;;
          aarch64|arm64) SB_ARCH=linux-arm64 ;;
          *) echo "✖ unsupported arch"; exit 1 ;;
        esac

        # тег последнего релиза (vX.Y.Z / vX.Y.Z-beta.N)
        VERSION=$(curl -sSL https://api.github.com/repos/SagerNet/sing-box/releases/latest \
                   | grep -Po '"tag_name":\s*"\K[^"]+')
        VNUM=${VERSION#v}

        URL="https://github.com/SagerNet/sing-box/releases/download/${VERSION}/sing-box-${VNUM}-${SB_ARCH}"
        echo "⬇  $URL"
        curl -sSL "$URL" -o /usr/local/bin/sing-box
        chmod +x /usr/local/bin/sing-box
        sing-box version                # проверка

    # ─── 4. Python-зависимости ─────────────────────────────────────────────
    - name: Install Python deps
      run: pip install --quiet pyyaml

    # ─── 5. Запуск фильтра ─────────────────────────────────────────────────
    - name: Run proxy filter
      run: python test_servers.py --output output/Server.txt

    # ─── 6. Коммит результата ──────────────────────────────────────────────
    - uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "chore: update proxy lists [skip ci]"
        file_pattern: |
          output/Server.txt
          output/latency_full.csv
        push_options: '--force-with-lease'

    # ─── 7. Прикладываем артефакты ─────────────────────────────────────────
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: proxy-results
        path: |
          output/Server.txt
          output/latency_full.csv