name: Proxy Filter

on:
  schedule:
    - cron:  '0 * * * *'           # каждый час
  push:          { branches: [ main ] }
  workflow_dispatch:

concurrency:     { group: proxy-filter, cancel-in-progress: true }

jobs:
  filter:
    runs-on: ubuntu-latest
    permissions: { contents: write }

    steps:
    # ── 1. код репозитория ────────────────────────────────────────────────
    - uses: actions/checkout@v4

    # ── 2. Python 3.12 ────────────────────────────────────────────────────
    - uses: actions/setup-python@v5
      with: { python-version: '3.12' }

    # ── 3. Установка sing-box (универсальный способ) ─────────────────────
    - name: Install sing-box
      run: |
        set -euo pipefail
        case "$(uname -m)" in
          x86_64|amd64)  PATTERN=linux-amd64  ;;
          aarch64|arm64) PATTERN=linux-arm64  ;;
          *) echo "✖ unsupported arch"; exit 1 ;;
        esac

        ASSET_URL=$(curl -sSL https://api.github.com/repos/SagerNet/sing-box/releases/latest \
          | grep -Po '"browser_download_url":\s*"\K[^"]+' \
          | grep "$PATTERN" | head -n1)

        [ -z "$ASSET_URL" ] && { echo "✖ sing-box asset not found"; exit 1; }
        echo "⬇  $ASSET_URL"

        if [[ "$ASSET_URL" == *.tar.gz ]]; then
          curl -fsSL "$ASSET_URL" -o sb.tgz
          tar -xzf sb.tgz --wildcards --no-anchored 'sing-box' -C /usr/local/bin
        else
          curl -fsSL "$ASSET_URL" -o /usr/local/bin/sing-box
        fi

        chmod +x /usr/local/bin/sing-box
        sing-box version

    # ── 4. Python-зависимости ────────────────────────────────────────────
    - name: Install Python deps
      run: pip install --quiet pyyaml

    # ── 5. Запуск фильтра ────────────────────────────────────────────────
    - name: Run proxy filter
      run: python test_servers.py --output output/Server.txt

    # ── 6. Коммитим всё, что в output/ ───────────────────────────────────
    - uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "chore: update proxy lists [skip ci]"
        file_pattern: output/**
        push_options: '--force-with-lease'

    # ── 7. Артефакты на всякий случай ────────────────────────────────────
    - uses: actions/upload-artifact@v4
      if: always()
      with: { name: proxy-results, path: output/** }