name: Update Proxy List

on:
  schedule:
    - cron: "0 * * * *"  # Каждый час
  workflow_dispatch:      # Возможность ручного запуска

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Run proxy filter script
        run: python test_servers.py

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add Server.txt skipped.txt ping_debug.txt
          git commit -m "Update proxy lists $(date)"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
